spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: lakutina
    password: 5364
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8090