spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: 5364
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
kafka:
  topic-name: book-topic

server:
  port: 8091